import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const FILES = [
  "zepto dataset-Zepto.csv",
  "zepto dataset-Zepto Super saver.csv",
];
const OUT = resolve(ROOT, "seed.ts");

function parseCsv(text) {
  const rows = [];
  let field = "";
  let row = [];
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += c;
      }
    } else {
      if (c === '"') {
        inQuotes = true;
      } else if (c === ",") {
        row.push(field);
        field = "";
      } else if (c === "\n") {
        row.push(field);
        rows.push(row);
        row = [];
        field = "";
      } else if (c === "\r") {
        // skip
      } else {
        field += c;
      }
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

function toNumber(v) {
  if (v === undefined || v === null) return 0;
  const s = String(v).trim().replace(/,/g, "");
  if (s === "") return 0;
  const n = Number(s);
  return Number.isFinite(n) ? n : 0;
}

function slugify(s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

const products = [];
const byKey = new Map();

const norm = (s) => String(s ?? "").toLowerCase().replace(/\s+/g, " ").trim();

for (const file of FILES) {
  const path = resolve(ROOT, file);
  const text = readFileSync(path, "utf8");
  const rows = parseCsv(text);
  if (rows.length === 0) continue;

  let iImage, iName, iPrice, iOrig, iRating, iReview, iQty, iStatus, iSub, iCat, iInter;
  const applyHeader = (h) => {
    const idx = (name) => h.indexOf(name);
    iImage = idx("Image");
    iName = idx("Name");
    iPrice = idx("Price");
    iOrig = idx("Original Price");
    iRating = idx("Ratings");
    iReview = idx("Review");
    iQty = idx("Quantity");
    iStatus = idx("Status");
    iSub = idx("Sub-Category");
    iCat = idx("Category");
    iInter = idx("Interface");
  };
  applyHeader(rows[0].map((h) => h.trim()));

  for (let r = 1; r < rows.length; r++) {
    const row = rows[r];
    if (row.length === 1 && row[0] === "") continue;
    if (row[0] === "Image" && row[1] === "Name") {
      applyHeader(row.map((h) => h.trim()));
      continue;
    }
    if (!row[iName]) continue;
    const interfaceName = (row[iInter] || "").trim();
    const name = (row[iName] || "").trim();
    const qty = (row[iQty] || "").trim();
    const id = `${slugify(interfaceName)}-${slugify(name)}-${slugify(qty)}`;
    const candidate = {
      id,
      image: (row[iImage] || "").trim(),
      name,
      price: toNumber(row[iPrice]),
      originalPrice: toNumber(row[iOrig]),
      rating: toNumber(row[iRating]),
      reviewCount: toNumber(row[iReview]),
      quantity: qty,
      status: (row[iStatus] || "").trim(),
      subCategory: (row[iSub] || "").trim(),
      category: (row[iCat] || "").trim(),
      interface: interfaceName,
    };

    const key = `${norm(name)}|${norm(qty)}`;
    const existing = byKey.get(key);
    if (!existing) {
      byKey.set(key, candidate);
      continue;
    }
    // Dedupe across CSVs: keep cheaper; tie-break on more reviews.
    const better =
      candidate.price && (!existing.price || candidate.price < existing.price)
        ? candidate
        : candidate.price === existing.price && candidate.reviewCount > existing.reviewCount
          ? candidate
          : existing;
    byKey.set(key, better);
  }
}

products.push(...byKey.values());

const header = `// @ts-nocheck
// AUTO-GENERATED by scripts/build-seed.mjs from the two Zepto CSV files.
// Do not edit by hand — re-run \`node scripts/build-seed.mjs\` to regenerate.

export type SeedProduct = {
  id: string;
  image: string;
  name: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviewCount: number;
  quantity: string;
  status: string;
  subCategory: string;
  category: string;
  interface: "Zepto" | "Zepto Super Saver";
};

export const products: SeedProduct[] = `;

const body = JSON.stringify(products, null, 2);
const footer = `;\n\nexport default products;\n`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, header + body + footer, "utf8");

const counts = products.reduce((acc, p) => {
  acc[p.interface] = (acc[p.interface] || 0) + 1;
  return acc;
}, {});
console.log(`Wrote ${products.length} products to ${OUT}`);
console.log("By interface:", counts);
